/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author luiz
 */
public class Main extends javax.swing.JFrame {
    
    private String lastPnl = "";
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlBookings = new javax.swing.JPanel();
        lblBooTitle = new javax.swing.JLabel();
        lblBooSearch = new javax.swing.JLabel();
        txtBooSearch = new javax.swing.JTextField();
        scrBooBookings = new javax.swing.JScrollPane();
        lstBooBooking = new javax.swing.JList<>();
        bttBooRegister = new javax.swing.JButton();
        bttBooEdit = new javax.swing.JButton();
        bttBooDelete = new javax.swing.JButton();
        sepBoo = new javax.swing.JSeparator();
        bttBooClients = new javax.swing.JButton();
        bttBooServices = new javax.swing.JButton();
        pnlClients = new javax.swing.JPanel();
        lblCliTitle = new javax.swing.JLabel();
        lblCliSearch = new javax.swing.JLabel();
        txtCliSearch = new javax.swing.JTextField();
        scrCliClients = new javax.swing.JScrollPane();
        lstCliClient = new javax.swing.JList<>();
        bttCliRegister = new javax.swing.JButton();
        bttCliEdit = new javax.swing.JButton();
        bttCliDelete = new javax.swing.JButton();
        bttCliBack = new javax.swing.JButton();
        pnlServices = new javax.swing.JPanel();
        lblSerTitle = new javax.swing.JLabel();
        lblSerSearch = new javax.swing.JLabel();
        txtSerSearch = new javax.swing.JTextField();
        scrSerServices = new javax.swing.JScrollPane();
        lstSerService = new javax.swing.JList<>();
        bttSerRegister = new javax.swing.JButton();
        bttSerEdit = new javax.swing.JButton();
        bttSerDelete = new javax.swing.JButton();
        bttSerBack = new javax.swing.JButton();
        pnlRegisterBooking = new javax.swing.JPanel();
        lblRegBooTitle = new javax.swing.JLabel();
        lblRegBooDate = new javax.swing.JLabel();
        dateChoRegBooDate = new datechooser.beans.DateChooserCombo();
        lblRegBooClient = new javax.swing.JLabel();
        txtRegBooClient = new javax.swing.JTextField();
        scrRegBooClients = new javax.swing.JScrollPane();
        lstRegBooClient = new javax.swing.JList<>();
        lblRegBooService = new javax.swing.JLabel();
        txtRegBooService = new javax.swing.JTextField();
        scrRegBooServices = new javax.swing.JScrollPane();
        lstRegBooService = new javax.swing.JList<>();
        bttRegBooRegister = new javax.swing.JButton();
        bttRegBooCancel = new javax.swing.JButton();
        pnlRegisterClient = new javax.swing.JPanel();
        lblRegCliTitle = new javax.swing.JLabel();
        lblRegCliName = new javax.swing.JLabel();
        txtRegCliName = new javax.swing.JTextField();
        lblRegCliPhone = new javax.swing.JLabel();
        txtRegCliPhone = new javax.swing.JTextField();
        lblRegCliSocialMedia = new javax.swing.JLabel();
        txtRegCliSocialMedia = new javax.swing.JTextField();
        lblRegCliAddress = new javax.swing.JLabel();
        sepRegCli = new javax.swing.JSeparator();
        lblRegCliStreet = new javax.swing.JLabel();
        txtRegCliStreet = new javax.swing.JTextField();
        lblRegCliNumber = new javax.swing.JLabel();
        txtRegCliNumber = new javax.swing.JTextField();
        lblRegCliComplement = new javax.swing.JLabel();
        txtRegCliComplement = new javax.swing.JTextField();
        lblRegCliNeighborhood = new javax.swing.JLabel();
        txtRegCliNeighborhood = new javax.swing.JTextField();
        lblRegCliCity = new javax.swing.JLabel();
        txtRegCliCity = new javax.swing.JTextField();
        bttRegCliRegister = new javax.swing.JButton();
        bttRegCliCancel = new javax.swing.JButton();
        pnlRegisterService = new javax.swing.JPanel();
        lblRegSerTitle = new javax.swing.JLabel();
        lblRegSerName = new javax.swing.JLabel();
        txtRegSerName = new javax.swing.JTextField();
        lblRegSerPrice = new javax.swing.JLabel();
        txtRegSerPrice = new javax.swing.JTextField();
        bttRegSerRegister = new javax.swing.JButton();
        bttRegSerCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setLayout(new java.awt.CardLayout());

        pnlBookings.setBackground(new java.awt.Color(255, 255, 255));
        pnlBookings.setName("bookings"); // NOI18N

        lblBooTitle.setBackground(new java.awt.Color(102, 0, 153));
        lblBooTitle.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblBooTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblBooTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBooTitle.setText("Reservas");
        lblBooTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblBooTitle.setName(""); // NOI18N
        lblBooTitle.setOpaque(true);

        lblBooSearch.setForeground(new java.awt.Color(102, 0, 153));
        lblBooSearch.setText("Buscar reserva");
        lblBooSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lstBooBooking.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrBooBookings.setViewportView(lstBooBooking);

        bttBooRegister.setBackground(new java.awt.Color(102, 0, 153));
        bttBooRegister.setForeground(new java.awt.Color(255, 255, 255));
        bttBooRegister.setText("Reservar");
        bttBooRegister.setBorderPainted(false);
        bttBooRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttBooRegisterActionPerformed(evt);
            }
        });

        bttBooEdit.setBackground(new java.awt.Color(102, 0, 153));
        bttBooEdit.setForeground(new java.awt.Color(255, 255, 255));
        bttBooEdit.setText("Editar");
        bttBooEdit.setBorderPainted(false);
        bttBooEdit.setEnabled(false);
        bttBooEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttBooEditActionPerformed(evt);
            }
        });

        bttBooDelete.setBackground(new java.awt.Color(102, 0, 153));
        bttBooDelete.setForeground(new java.awt.Color(255, 255, 255));
        bttBooDelete.setText("Excluir");
        bttBooDelete.setBorderPainted(false);
        bttBooDelete.setEnabled(false);

        sepBoo.setForeground(new java.awt.Color(153, 153, 153));

        bttBooClients.setBackground(new java.awt.Color(102, 0, 153));
        bttBooClients.setForeground(new java.awt.Color(255, 255, 255));
        bttBooClients.setText("Clientes");
        bttBooClients.setBorderPainted(false);
        bttBooClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttBooClientsActionPerformed(evt);
            }
        });

        bttBooServices.setBackground(new java.awt.Color(102, 0, 153));
        bttBooServices.setForeground(new java.awt.Color(255, 255, 255));
        bttBooServices.setText("Serviços");
        bttBooServices.setBorderPainted(false);
        bttBooServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttBooServicesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBookingsLayout = new javax.swing.GroupLayout(pnlBookings);
        pnlBookings.setLayout(pnlBookingsLayout);
        pnlBookingsLayout.setHorizontalGroup(
            pnlBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBooTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBookingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBookingsLayout.createSequentialGroup()
                        .addGroup(pnlBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(scrBooBookings, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBooSearch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(txtBooSearch, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBookingsLayout.createSequentialGroup()
                        .addGap(0, 31, Short.MAX_VALUE)
                        .addGroup(pnlBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bttBooDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlBookingsLayout.createSequentialGroup()
                                    .addComponent(bttBooClients, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(bttBooServices, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBookingsLayout.createSequentialGroup()
                                    .addComponent(bttBooRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(bttBooEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(sepBoo))
                        .addGap(43, 43, 43))))
        );
        pnlBookingsLayout.setVerticalGroup(
            pnlBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBookingsLayout.createSequentialGroup()
                .addComponent(lblBooTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblBooSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBooSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrBooBookings, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttBooRegister)
                    .addComponent(bttBooEdit))
                .addGap(18, 18, 18)
                .addComponent(bttBooDelete)
                .addGap(18, 18, 18)
                .addComponent(sepBoo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttBooServices)
                    .addComponent(bttBooClients))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pnlMain.add(pnlBookings, "card1");

        pnlClients.setBackground(new java.awt.Color(255, 255, 255));
        pnlClients.setName("clients"); // NOI18N

        lblCliTitle.setBackground(new java.awt.Color(102, 0, 153));
        lblCliTitle.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCliTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblCliTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCliTitle.setText("Clientes");
        lblCliTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCliTitle.setName(""); // NOI18N
        lblCliTitle.setOpaque(true);

        lblCliSearch.setForeground(new java.awt.Color(102, 0, 153));
        lblCliSearch.setText("Buscar cliente");
        lblCliSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lstCliClient.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrCliClients.setViewportView(lstCliClient);

        bttCliRegister.setBackground(new java.awt.Color(102, 0, 153));
        bttCliRegister.setForeground(new java.awt.Color(255, 255, 255));
        bttCliRegister.setText("Cadastrar");
        bttCliRegister.setBorderPainted(false);
        bttCliRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCliRegisterActionPerformed(evt);
            }
        });

        bttCliEdit.setBackground(new java.awt.Color(102, 0, 153));
        bttCliEdit.setForeground(new java.awt.Color(255, 255, 255));
        bttCliEdit.setText("Editar");
        bttCliEdit.setBorderPainted(false);
        bttCliEdit.setEnabled(false);
        bttCliEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCliEditActionPerformed(evt);
            }
        });

        bttCliDelete.setBackground(new java.awt.Color(102, 0, 153));
        bttCliDelete.setForeground(new java.awt.Color(255, 255, 255));
        bttCliDelete.setText("Excluir");
        bttCliDelete.setBorderPainted(false);
        bttCliDelete.setEnabled(false);
        bttCliDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCliDeleteActionPerformed(evt);
            }
        });

        bttCliBack.setBackground(new java.awt.Color(255, 255, 255));
        bttCliBack.setForeground(new java.awt.Color(102, 0, 153));
        bttCliBack.setText("Voltar");
        bttCliBack.setBorderPainted(false);
        bttCliBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCliBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlClientsLayout = new javax.swing.GroupLayout(pnlClients);
        pnlClients.setLayout(pnlClientsLayout);
        pnlClientsLayout.setHorizontalGroup(
            pnlClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCliTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
            .addGroup(pnlClientsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCliSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCliSearch)
                    .addComponent(scrCliClients))
                .addContainerGap())
            .addGroup(pnlClientsLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(pnlClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlClientsLayout.createSequentialGroup()
                        .addComponent(bttCliDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bttCliBack, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlClientsLayout.createSequentialGroup()
                        .addComponent(bttCliRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bttCliEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlClientsLayout.setVerticalGroup(
            pnlClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientsLayout.createSequentialGroup()
                .addComponent(lblCliTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCliSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCliSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrCliClients, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttCliRegister)
                    .addComponent(bttCliEdit))
                .addGap(18, 18, 18)
                .addGroup(pnlClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttCliBack)
                    .addComponent(bttCliDelete))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pnlMain.add(pnlClients, "card2");

        pnlServices.setBackground(new java.awt.Color(255, 255, 255));
        pnlServices.setName("services"); // NOI18N

        lblSerTitle.setBackground(new java.awt.Color(102, 0, 153));
        lblSerTitle.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSerTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblSerTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSerTitle.setText("Serviços");
        lblSerTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSerTitle.setName(""); // NOI18N
        lblSerTitle.setOpaque(true);

        lblSerSearch.setForeground(new java.awt.Color(102, 0, 153));
        lblSerSearch.setText("Buscar serviço");
        lblSerSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lstSerService.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrSerServices.setViewportView(lstSerService);

        bttSerRegister.setBackground(new java.awt.Color(102, 0, 153));
        bttSerRegister.setForeground(new java.awt.Color(255, 255, 255));
        bttSerRegister.setText("Cadastrar");
        bttSerRegister.setBorderPainted(false);
        bttSerRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSerRegisterActionPerformed(evt);
            }
        });

        bttSerEdit.setBackground(new java.awt.Color(102, 0, 153));
        bttSerEdit.setForeground(new java.awt.Color(255, 255, 255));
        bttSerEdit.setText("Editar");
        bttSerEdit.setBorderPainted(false);
        bttSerEdit.setEnabled(false);
        bttSerEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSerEditActionPerformed(evt);
            }
        });

        bttSerDelete.setBackground(new java.awt.Color(102, 0, 153));
        bttSerDelete.setForeground(new java.awt.Color(255, 255, 255));
        bttSerDelete.setText("Excluir");
        bttSerDelete.setBorderPainted(false);
        bttSerDelete.setEnabled(false);
        bttSerDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSerDeleteActionPerformed(evt);
            }
        });

        bttSerBack.setBackground(new java.awt.Color(255, 255, 255));
        bttSerBack.setForeground(new java.awt.Color(102, 0, 153));
        bttSerBack.setText("Voltar");
        bttSerBack.setBorderPainted(false);
        bttSerBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSerBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlServicesLayout = new javax.swing.GroupLayout(pnlServices);
        pnlServices.setLayout(pnlServicesLayout);
        pnlServicesLayout.setHorizontalGroup(
            pnlServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSerTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
            .addGroup(pnlServicesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSerSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSerSearch)
                    .addComponent(scrSerServices))
                .addContainerGap())
            .addGroup(pnlServicesLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(pnlServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlServicesLayout.createSequentialGroup()
                        .addComponent(bttSerDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bttSerBack, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlServicesLayout.createSequentialGroup()
                        .addComponent(bttSerRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bttSerEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlServicesLayout.setVerticalGroup(
            pnlServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServicesLayout.createSequentialGroup()
                .addComponent(lblSerTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSerSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSerSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrSerServices, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttSerRegister)
                    .addComponent(bttSerEdit))
                .addGap(18, 18, 18)
                .addGroup(pnlServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttSerBack)
                    .addComponent(bttSerDelete))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pnlMain.add(pnlServices, "card3");

        pnlRegisterBooking.setBackground(new java.awt.Color(255, 255, 255));
        pnlRegisterBooking.setName("registerBooking"); // NOI18N

        lblRegBooTitle.setBackground(new java.awt.Color(102, 0, 153));
        lblRegBooTitle.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblRegBooTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblRegBooTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegBooTitle.setText("Reserva de Horário");
        lblRegBooTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblRegBooTitle.setName(""); // NOI18N
        lblRegBooTitle.setOpaque(true);

        lblRegBooDate.setForeground(new java.awt.Color(102, 0, 153));
        lblRegBooDate.setText("Data");

        lblRegBooClient.setForeground(new java.awt.Color(102, 0, 153));
        lblRegBooClient.setText("Cliente");

        lstRegBooClient.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrRegBooClients.setViewportView(lstRegBooClient);

        lblRegBooService.setForeground(new java.awt.Color(102, 0, 153));
        lblRegBooService.setText("Serviço");

        lstRegBooService.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrRegBooServices.setViewportView(lstRegBooService);

        bttRegBooRegister.setBackground(new java.awt.Color(102, 0, 153));
        bttRegBooRegister.setForeground(new java.awt.Color(255, 255, 255));
        bttRegBooRegister.setText("Reservar");
        bttRegBooRegister.setBorderPainted(false);
        bttRegBooRegister.setEnabled(false);
        bttRegBooRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttRegBooRegisterActionPerformed(evt);
            }
        });

        bttRegBooCancel.setBackground(new java.awt.Color(255, 255, 255));
        bttRegBooCancel.setForeground(new java.awt.Color(102, 0, 153));
        bttRegBooCancel.setText("Cancelar");
        bttRegBooCancel.setBorderPainted(false);
        bttRegBooCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttRegBooCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegisterBookingLayout = new javax.swing.GroupLayout(pnlRegisterBooking);
        pnlRegisterBooking.setLayout(pnlRegisterBookingLayout);
        pnlRegisterBookingLayout.setHorizontalGroup(
            pnlRegisterBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegBooTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
            .addGroup(pnlRegisterBookingLayout.createSequentialGroup()
                .addGroup(pnlRegisterBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegisterBookingLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(pnlRegisterBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblRegBooDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRegBooClient, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(dateChoRegBooDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtRegBooClient)
                            .addComponent(scrRegBooClients)
                            .addComponent(lblRegBooService, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(txtRegBooService)
                            .addComponent(scrRegBooServices)))
                    .addGroup(pnlRegisterBookingLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(bttRegBooRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bttRegBooCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlRegisterBookingLayout.setVerticalGroup(
            pnlRegisterBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterBookingLayout.createSequentialGroup()
                .addComponent(lblRegBooTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblRegBooDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateChoRegBooDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRegBooClient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRegBooClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrRegBooClients, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRegBooService)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRegBooService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrRegBooServices, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlRegisterBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttRegBooCancel)
                    .addComponent(bttRegBooRegister))
                .addGap(0, 81, Short.MAX_VALUE))
        );

        pnlMain.add(pnlRegisterBooking, "card4");

        pnlRegisterClient.setBackground(new java.awt.Color(255, 255, 255));
        pnlRegisterClient.setName("registerClient"); // NOI18N

        lblRegCliTitle.setBackground(new java.awt.Color(102, 0, 153));
        lblRegCliTitle.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblRegCliTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblRegCliTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegCliTitle.setText("Cadastro de Cliente");
        lblRegCliTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblRegCliTitle.setName(""); // NOI18N
        lblRegCliTitle.setOpaque(true);

        lblRegCliName.setForeground(new java.awt.Color(102, 0, 153));
        lblRegCliName.setText("Nome");

        lblRegCliPhone.setForeground(new java.awt.Color(102, 0, 153));
        lblRegCliPhone.setText("Celular");

        lblRegCliSocialMedia.setForeground(new java.awt.Color(102, 0, 153));
        lblRegCliSocialMedia.setText("Mídia Social");

        lblRegCliAddress.setForeground(new java.awt.Color(102, 0, 153));
        lblRegCliAddress.setText("Endereço");

        sepRegCli.setForeground(new java.awt.Color(153, 153, 153));

        lblRegCliStreet.setForeground(new java.awt.Color(102, 0, 153));
        lblRegCliStreet.setText("Logradouro");

        lblRegCliNumber.setForeground(new java.awt.Color(102, 0, 153));
        lblRegCliNumber.setText("Número");

        lblRegCliComplement.setForeground(new java.awt.Color(102, 0, 153));
        lblRegCliComplement.setText("Complemento");

        lblRegCliNeighborhood.setForeground(new java.awt.Color(102, 0, 153));
        lblRegCliNeighborhood.setText("Bairro");

        lblRegCliCity.setForeground(new java.awt.Color(102, 0, 153));
        lblRegCliCity.setText("Cidade");

        bttRegCliRegister.setBackground(new java.awt.Color(102, 0, 153));
        bttRegCliRegister.setForeground(new java.awt.Color(255, 255, 255));
        bttRegCliRegister.setText("Cadastrar");
        bttRegCliRegister.setBorderPainted(false);
        bttRegCliRegister.setEnabled(false);
        bttRegCliRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttRegCliRegisterActionPerformed(evt);
            }
        });

        bttRegCliCancel.setBackground(new java.awt.Color(255, 255, 255));
        bttRegCliCancel.setForeground(new java.awt.Color(102, 0, 153));
        bttRegCliCancel.setText("Cancelar");
        bttRegCliCancel.setBorderPainted(false);
        bttRegCliCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttRegCliCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegisterClientLayout = new javax.swing.GroupLayout(pnlRegisterClient);
        pnlRegisterClient.setLayout(pnlRegisterClientLayout);
        pnlRegisterClientLayout.setHorizontalGroup(
            pnlRegisterClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegCliTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlRegisterClientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRegisterClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRegCliStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlRegisterClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(sepRegCli, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRegCliAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblRegCliStreet, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblRegCliName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlRegisterClientLayout.createSequentialGroup()
                            .addGroup(pnlRegisterClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtRegCliPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblRegCliPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlRegisterClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblRegCliSocialMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtRegCliSocialMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(txtRegCliName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRegCliCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtRegCliNeighborhood, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRegCliNeighborhood, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlRegisterClientLayout.createSequentialGroup()
                            .addGroup(pnlRegisterClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblRegCliNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtRegCliNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlRegisterClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblRegCliComplement, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtRegCliComplement, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pnlRegisterClientLayout.createSequentialGroup()
                            .addComponent(bttRegCliRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(bttRegCliCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31))
                        .addComponent(txtRegCliCity, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlRegisterClientLayout.setVerticalGroup(
            pnlRegisterClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterClientLayout.createSequentialGroup()
                .addComponent(lblRegCliTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblRegCliName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRegCliName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRegisterClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRegCliPhone)
                    .addGroup(pnlRegisterClientLayout.createSequentialGroup()
                        .addComponent(lblRegCliSocialMedia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlRegisterClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRegCliSocialMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRegCliPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRegCliAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sepRegCli, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRegCliStreet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRegCliStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRegisterClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegisterClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblRegCliComplement)
                        .addComponent(lblRegCliNumber))
                    .addGroup(pnlRegisterClientLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnlRegisterClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRegCliNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRegCliComplement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRegCliNeighborhood)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRegCliNeighborhood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRegCliCity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRegCliCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlRegisterClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttRegCliCancel)
                    .addComponent(bttRegCliRegister))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pnlMain.add(pnlRegisterClient, "card5");

        pnlRegisterService.setBackground(new java.awt.Color(255, 255, 255));
        pnlRegisterService.setName("registerService"); // NOI18N

        lblRegSerTitle.setBackground(new java.awt.Color(102, 0, 153));
        lblRegSerTitle.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblRegSerTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblRegSerTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegSerTitle.setText("Cadastro de Serviço");
        lblRegSerTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblRegSerTitle.setName(""); // NOI18N
        lblRegSerTitle.setOpaque(true);

        lblRegSerName.setForeground(new java.awt.Color(102, 0, 153));
        lblRegSerName.setText("Nome");

        lblRegSerPrice.setForeground(new java.awt.Color(102, 0, 153));
        lblRegSerPrice.setText("Preço");

        bttRegSerRegister.setBackground(new java.awt.Color(102, 0, 153));
        bttRegSerRegister.setForeground(new java.awt.Color(255, 255, 255));
        bttRegSerRegister.setText("Cadastrar");
        bttRegSerRegister.setBorderPainted(false);
        bttRegSerRegister.setEnabled(false);
        bttRegSerRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttRegSerRegisterActionPerformed(evt);
            }
        });

        bttRegSerCancel.setBackground(new java.awt.Color(255, 255, 255));
        bttRegSerCancel.setForeground(new java.awt.Color(102, 0, 153));
        bttRegSerCancel.setText("Cancelar");
        bttRegSerCancel.setBorderPainted(false);
        bttRegSerCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttRegSerCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegisterServiceLayout = new javax.swing.GroupLayout(pnlRegisterService);
        pnlRegisterService.setLayout(pnlRegisterServiceLayout);
        pnlRegisterServiceLayout.setHorizontalGroup(
            pnlRegisterServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegSerTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegisterServiceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRegisterServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegisterServiceLayout.createSequentialGroup()
                        .addGroup(pnlRegisterServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRegSerPrice)
                            .addComponent(lblRegSerPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtRegSerName)
                            .addComponent(lblRegSerName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegisterServiceLayout.createSequentialGroup()
                        .addComponent(bttRegSerRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bttRegSerCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );
        pnlRegisterServiceLayout.setVerticalGroup(
            pnlRegisterServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterServiceLayout.createSequentialGroup()
                .addComponent(lblRegSerTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblRegSerName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRegSerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRegSerPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRegSerPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlRegisterServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttRegSerCancel)
                    .addComponent(bttRegSerRegister))
                .addGap(0, 255, Short.MAX_VALUE))
        );

        pnlMain.add(pnlRegisterService, "card6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alterScreen(javax.swing.JPanel pnl) {
        pnlMain.removeAll();
        pnlMain.add(pnl);
        pnlMain.repaint();
        pnlMain.revalidate();
        
        switch (pnl.getName()) {
            case "bookings":
                txtBooSearch.setText("");
                break;
                
            case "clients":
                txtCliSearch.setText("");
                break;
                
            case "services":
                txtSerSearch.setText("");
                break;
                
            case "registerBooking":
                dateChoRegBooDate.setMinDate(dateChoRegBooDate.getDefaultPeriods().getFirstDate());
                txtRegBooClient.setText("");
                txtRegBooService.setText("");
                break;
                
            case "registerClient":
                txtRegCliName.setText("");
                txtRegCliPhone.setText("");
                txtRegCliSocialMedia.setText("");
                txtRegCliStreet.setText("");
                txtRegCliNumber.setText("");
                txtRegCliComplement.setText("");
                txtRegCliNeighborhood.setText("");
                txtRegCliCity.setText("");
                break;
                
            case "registerService":
                txtRegSerName.setText("");
                txtRegSerPrice.setText("");
                break;
        }
    }

    private void bttBooRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttBooRegisterActionPerformed
        alterScreen(pnlRegisterBooking);
    }//GEN-LAST:event_bttBooRegisterActionPerformed

    private void bttBooClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttBooClientsActionPerformed
        lastPnl = pnlMain.getComponent(0).getName();
        alterScreen(pnlClients);
    }//GEN-LAST:event_bttBooClientsActionPerformed

    private void bttBooServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttBooServicesActionPerformed
        lastPnl = pnlMain.getComponent(0).getName();
        alterScreen(pnlServices);
    }//GEN-LAST:event_bttBooServicesActionPerformed

    private void bttBooEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttBooEditActionPerformed
        alterScreen(pnlRegisterBooking);
    }//GEN-LAST:event_bttBooEditActionPerformed

    private void bttCliRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCliRegisterActionPerformed
        alterScreen(pnlRegisterClient);
    }//GEN-LAST:event_bttCliRegisterActionPerformed

    private void bttCliBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCliBackActionPerformed
        switch (lastPnl) {
            case "bookings":
                alterScreen(pnlBookings);
                break;
                
            case "registerBooking":
                alterScreen(pnlRegisterBooking);
                break;
        }
    }//GEN-LAST:event_bttCliBackActionPerformed

    private void bttSerRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSerRegisterActionPerformed
        alterScreen(pnlRegisterService);
    }//GEN-LAST:event_bttSerRegisterActionPerformed

    private void bttSerBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSerBackActionPerformed
        alterScreen(pnlBookings);
    }//GEN-LAST:event_bttSerBackActionPerformed

    private void bttCliEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCliEditActionPerformed
        alterScreen(pnlRegisterClient);
    }//GEN-LAST:event_bttCliEditActionPerformed

    private void bttCliDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCliDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttCliDeleteActionPerformed

    private void bttSerEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSerEditActionPerformed
        alterScreen(pnlRegisterService);
    }//GEN-LAST:event_bttSerEditActionPerformed

    private void bttSerDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSerDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttSerDeleteActionPerformed

    private void bttRegBooRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttRegBooRegisterActionPerformed
        alterScreen(pnlBookings);
    }//GEN-LAST:event_bttRegBooRegisterActionPerformed

    private void bttRegBooCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttRegBooCancelActionPerformed
        alterScreen(pnlBookings);
    }//GEN-LAST:event_bttRegBooCancelActionPerformed

    private void bttRegSerRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttRegSerRegisterActionPerformed
        alterScreen(pnlServices);
    }//GEN-LAST:event_bttRegSerRegisterActionPerformed

    private void bttRegSerCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttRegSerCancelActionPerformed
        alterScreen(pnlServices);
    }//GEN-LAST:event_bttRegSerCancelActionPerformed

    private void bttRegCliCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttRegCliCancelActionPerformed
        alterScreen(pnlClients);
    }//GEN-LAST:event_bttRegCliCancelActionPerformed

    private void bttRegCliRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttRegCliRegisterActionPerformed
        alterScreen(pnlClients);
    }//GEN-LAST:event_bttRegCliRegisterActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttBooClients;
    private javax.swing.JButton bttBooDelete;
    private javax.swing.JButton bttBooEdit;
    private javax.swing.JButton bttBooRegister;
    private javax.swing.JButton bttBooServices;
    private javax.swing.JButton bttCliBack;
    private javax.swing.JButton bttCliDelete;
    private javax.swing.JButton bttCliEdit;
    private javax.swing.JButton bttCliRegister;
    private javax.swing.JButton bttRegBooCancel;
    private javax.swing.JButton bttRegBooRegister;
    private javax.swing.JButton bttRegCliCancel;
    private javax.swing.JButton bttRegCliRegister;
    private javax.swing.JButton bttRegSerCancel;
    private javax.swing.JButton bttRegSerRegister;
    private javax.swing.JButton bttSerBack;
    private javax.swing.JButton bttSerDelete;
    private javax.swing.JButton bttSerEdit;
    private javax.swing.JButton bttSerRegister;
    private datechooser.beans.DateChooserCombo dateChoRegBooDate;
    private javax.swing.JLabel lblBooSearch;
    private javax.swing.JLabel lblBooTitle;
    private javax.swing.JLabel lblCliSearch;
    private javax.swing.JLabel lblCliTitle;
    private javax.swing.JLabel lblRegBooClient;
    private javax.swing.JLabel lblRegBooDate;
    private javax.swing.JLabel lblRegBooService;
    private javax.swing.JLabel lblRegBooTitle;
    private javax.swing.JLabel lblRegCliAddress;
    private javax.swing.JLabel lblRegCliCity;
    private javax.swing.JLabel lblRegCliComplement;
    private javax.swing.JLabel lblRegCliName;
    private javax.swing.JLabel lblRegCliNeighborhood;
    private javax.swing.JLabel lblRegCliNumber;
    private javax.swing.JLabel lblRegCliPhone;
    private javax.swing.JLabel lblRegCliSocialMedia;
    private javax.swing.JLabel lblRegCliStreet;
    private javax.swing.JLabel lblRegCliTitle;
    private javax.swing.JLabel lblRegSerName;
    private javax.swing.JLabel lblRegSerPrice;
    private javax.swing.JLabel lblRegSerTitle;
    private javax.swing.JLabel lblSerSearch;
    private javax.swing.JLabel lblSerTitle;
    private javax.swing.JList<String> lstBooBooking;
    private javax.swing.JList<String> lstCliClient;
    private javax.swing.JList<String> lstRegBooClient;
    private javax.swing.JList<String> lstRegBooService;
    private javax.swing.JList<String> lstSerService;
    private javax.swing.JPanel pnlBookings;
    private javax.swing.JPanel pnlClients;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlRegisterBooking;
    private javax.swing.JPanel pnlRegisterClient;
    private javax.swing.JPanel pnlRegisterService;
    private javax.swing.JPanel pnlServices;
    private javax.swing.JScrollPane scrBooBookings;
    private javax.swing.JScrollPane scrCliClients;
    private javax.swing.JScrollPane scrRegBooClients;
    private javax.swing.JScrollPane scrRegBooServices;
    private javax.swing.JScrollPane scrSerServices;
    private javax.swing.JSeparator sepBoo;
    private javax.swing.JSeparator sepRegCli;
    private javax.swing.JTextField txtBooSearch;
    private javax.swing.JTextField txtCliSearch;
    private javax.swing.JTextField txtRegBooClient;
    private javax.swing.JTextField txtRegBooService;
    private javax.swing.JTextField txtRegCliCity;
    private javax.swing.JTextField txtRegCliComplement;
    private javax.swing.JTextField txtRegCliName;
    private javax.swing.JTextField txtRegCliNeighborhood;
    private javax.swing.JTextField txtRegCliNumber;
    private javax.swing.JTextField txtRegCliPhone;
    private javax.swing.JTextField txtRegCliSocialMedia;
    private javax.swing.JTextField txtRegCliStreet;
    private javax.swing.JTextField txtRegSerName;
    private javax.swing.JTextField txtRegSerPrice;
    private javax.swing.JTextField txtSerSearch;
    // End of variables declaration//GEN-END:variables
}
